matrix:
  include:
    - os: linux
      dist: trusty
      language: python
      python: "2.7"
      env: CFLAGS="-std=c90 -pedantic -Wno-long-long -Werror"
    - os: linux
      dist: trusty
      language: python
      python: "3.3"
      env: CFLAGS="-std=c90 -pedantic -Wno-long-long -Werror"
    - os: linux
      dist: trusty
      language: python
      python: "3.4"
      env: CFLAGS="-std=c90 -pedantic -Wno-long-long -Werror"
    - os: linux
      dist: trusty
      language: python
      python: "3.5"
      env: CFLAGS="-std=c90 -pedantic -Wno-long-long -Werror"
    - os: linux
      dist: trusty
      language: python
      python: "3.6"

install:
  - travis_retry sudo apt-get update -q
  - travis_retry sudo apt-get install -y libcairo2-dev
  - python -m pip install --upgrade pytest

script:
  - python setup.py test
